[package]
name = "leptos-alert-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
console_error_panic_hook = "0.1.7"
alert-rs = { path = "../../", features = ["lep"] }
leptos = { version = "0.7.2", features = ["csr"] }
log = "0.4.22"
wasm-logger = "0.2.0"
